### ISSUE TITLE
Feature Request: Mod Only commands

### ISSUE THREAD

**Issue by r3ne-pew** [MiniDigger/KatzenBot#2]
Michi will Commands auf Mod only schalten können

**Comment by MiniDigger** [comment]
MemoryCommands sind standardmäßig auf "all" gestellt, könnten aber in der datei auch auf op gestellt werden, dann können nur bot operators (!op <name>) den command ausführen. 
reicht dass oder soll ich den code ändern damit man ein argument angeben kann dass nur ops den neuen command benutzen können?

**Comment by r3ne-pew** [comment]
Änderung so, dass man die Berechtigung einstellen kann - sowohl beim erstellen als auch nacher
